# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Enterv3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EnterWindow(object):
    def setupUi(self, EnterWindow):
        EnterWindow.setObjectName("EnterWindow")
        EnterWindow.setFixedSize(220, 288)
        self.centralwidget = QtWidgets.QWidget(EnterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineFam = QtWidgets.QLineEdit(self.centralwidget)
        self.lineFam.setGeometry(QtCore.QRect(30, 30, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineFam.setFont(font)
        self.lineFam.setObjectName("lineFam")
        self.lineName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineName.setGeometry(QtCore.QRect(30, 80, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineName.setFont(font)
        self.lineName.setObjectName("lineName")
        self.linePass = QtWidgets.QLineEdit(self.centralwidget)
        self.linePass.setGeometry(QtCore.QRect(30, 130, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.linePass.setFont(font)
        self.linePass.setObjectName("linePass")
        self.buttonEnter = QtWidgets.QPushButton(self.centralwidget)
        self.buttonEnter.setGeometry(QtCore.QRect(50, 170, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonEnter.setFont(font)
        self.buttonEnter.setObjectName("buttonEnter")
        self.lbFam = QtWidgets.QLabel(self.centralwidget)
        self.lbFam.setGeometry(QtCore.QRect(30, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbFam.setFont(font)
        self.lbFam.setObjectName("lbFam")
        self.lbName = QtWidgets.QLabel(self.centralwidget)
        self.lbName.setGeometry(QtCore.QRect(30, 60, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbName.setFont(font)
        self.lbName.setObjectName("lbName")
        self.lbPass = QtWidgets.QLabel(self.centralwidget)
        self.lbPass.setGeometry(QtCore.QRect(30, 110, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbPass.setFont(font)
        self.lbPass.setObjectName("lbPass")
        self.buttonRegistration = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRegistration.setGeometry(QtCore.QRect(50, 220, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonRegistration.setFont(font)
        self.buttonRegistration.setObjectName("buttonRegistration")
        EnterWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EnterWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 220, 18))
        self.menubar.setObjectName("menubar")
        EnterWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EnterWindow)
        self.statusbar.setObjectName("statusbar")
        EnterWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EnterWindow)
        QtCore.QMetaObject.connectSlotsByName(EnterWindow)

    def retranslateUi(self, EnterWindow):
        _translate = QtCore.QCoreApplication.translate
        EnterWindow.setWindowTitle(_translate("EnterWindow", "Вход"))
        self.buttonEnter.setText(_translate("EnterWindow", "Вход"))
        self.lbFam.setText(_translate("EnterWindow", "Фамилия"))
        self.lbName.setText(_translate("EnterWindow", "Имя"))
        self.lbPass.setText(_translate("EnterWindow", "Пароль"))
        self.buttonRegistration.setText(_translate("EnterWindow", "Регистрация"))
